<?php
return array (
  'load_ext_config' => 
  array (
    'home' => 'home',
  ),
  'active_plugin' => '',
  'official_website' => 'http://data.jdcms.com/',
  'cms_name' => '简单CMS',
  'cms_domain' => '',
  'cms_versions' => 'V1.3',
  'web_path' => '/',
  'db_host' => 'localhost',
  'db_port' => '3306',
  'db_user' => 'root',
  'db_pwd' => '',
  'db_name' => 'jdcms',
  'db_prefix' => 'jd_',
  'site_name' => '简单CMS',
  'site_domain' => '',
  'site_title' => '简单CMS_全球最大的中国女性购物社区，分享网购乐趣，发现潮流精品。',
  'site_keyword' => '购物，交友，分享社区。',
  'site_description' => '简单CMS官方网站，全球最大的中的女性购物社区，上千万女性会员一起发现时尚至IN的扮美单品，交流最新最热的时尚穿搭，分享在各大购物网站的网购经验。',
  'default_kw' => '宝贝、专辑...',
  'site_icp' => '',
  'statistics_code' => '<script src="http://s13.cnzz.com/stat.php?id=4511326&web_id=4511326&show=pic" language="JavaScript"></script>',
  'record' => 'copyright ©2012 All Rights Reserved.',
  'site_status' => '1',
  'comments_status' => '0',
  'items_status' => '0',
  'album_status' => '0',
  'down_status' => '0',
  'article_show' => '0',
  'tmpl_action_error' => './App/Tpl/Admin/jump.html',
  'tmpl_action_success' => './App/Tpl/Admin/jump.html',
  'sina_appkey' => '662835029',
  'sina_appsecret' => 'e3b92626b30b1a58795daf312e21df31',
  'taobao_appkey' => '21108506',
  'taobao_appsecret' => '5f29c86c15cf8e79c095c01416574a89',
  'taobaoke_nick' => '',
  'taobaoke_pid' => '33618674',
  'qq_appkey' => '100321020',
  'qq_appsecret' => 'efc7939403fdda2dca7a7b5d5b198bcc',
  'paipaike_pid' => '',
  'follow_us' => '<a href=\'http://weibo.com/jdcms\'>新浪微博</a>',
  'follow_us2' => '',
  'follow_us3' => '',
  'follow_us4' => '',
  'follow_us5' => '',
  'follow_us6' => '',
  'new_visit' => '1',
  'push_request' => '{"cate":"\\u8863\\u670d-1-1 \\u978b\\u5b50-2-1 \\u5305\\u5305-3-1 \\u914d\\u9970-4-1 \\u7f8e\\u5986-5-1 \\u5bb6\\u5c45-6-1","cps":"0","price":"0","nums":"100","auto_push":"1"}',
  'spread_status' => '0',
  'spread_position' => '1',
  'filter' => '走私,混蛋',
  'login_key' => 'jdcms',
);
?>